version: '3'

services:

  db:
    image: postgres:alpine
    container_name: voltz-challange-postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_LOCAL: ${POSTGRES_LOCAL}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voltz-challange-nest-app-container
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/api/src

volumes:
  postgres-data:
