#!/bin/sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")
pattern="^(chore|docs|feat|fix|refactor|style|test):"
if ! [[ $commit_msg =~ $pattern ]]; then
  echo "Erro: A mensagem de commit não possui um prefixo válido (feat, chore, fix, etc...)"
  exit 1
fi